<a href="https://colab.research.google.com/github/Halak29-6/AI_ML-Training-Batch1/blob/main/Homework/EDA_using_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

`Exploratory Data analysis (EDA) using Pandas`

In [18]:
import pandas as pd
import numpy as np

In [19]:
data = {
    'Employee_ID': [101, 102, 103, 104, 105, 106, 107, 104],
    'Age': [25, np.nan, 30, 45, 30, 22, 50, 45],
    'Salary': [50000, 60000, 55000, 80000, 55000, np.nan, 90000, 80000],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'IT', 'HR', 'Finance', 'Finance'],
    'Name': ['Halak', 'Smith', 'Michael ', 'abhishek', 'Riya' , 'Emily' , 'Daniel','george']
}
df = pd.DataFrame(data)

In [20]:
print(df.head())

   Employee_ID   Age   Salary Department      Name
0          101  25.0  50000.0         IT     Halak
1          102   NaN  60000.0         HR     Smith
2          103  30.0  55000.0         IT  Michael
3          104  45.0  80000.0    Finance  abhishek
4          105  30.0  55000.0         IT      Riya

In [21]:
print(f"\nDataset Shape: {df.shape}")

Dataset Shape: (8, 5)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  8 non-null      int64
 1   Age          7 non-null      float64
 2   Salary       7 non-null      float64
 3   Department   8 non-null      object
 4   Name         8 non-null      object
dtypes: float64(2), int64(1), object(2)
memory usage: 452.0+ bytes

In [32]:
print(df.describe().T)

             count          mean           std      min       25%      50%  \
Employee_ID    8.0    104.000000      2.000000    101.0    102.75    104.0
Age            7.0     35.285714     11.131252     22.0     27.50     30.0
Salary         7.0  67142.857143  15773.697214  50000.0  55000.00  60000.0

                  75%      max
Employee_ID    105.25    107.0
Age             45.00     50.0
Salary       80000.00  90000.0

In [24]:
df.isnull()

   Employee_ID    Age  Salary  Department   Name
0        False  False   False       False  False
1        False   True   False       False  False
2        False  False   False       False  False
3        False  False   False       False  False
4        False  False   False       False  False
5        False  False    True       False  False
6        False  False   False       False  False
7        False  False   False       False  False

In [25]:
df.isnull().sum()

Employee_ID    0
Age            1
Salary         1
Department     0
Name           0
dtype: int64

In [26]:
print(df.isnull().sum())

Employee_ID    0
Age            1
Salary         1
Department     0
Name           0
dtype: int64

In [27]:

duplicate_count = df.duplicated().sum()

In [28]:

df_cleaned = df.drop_duplicates()
df_cleaned['Age'] = df_cleaned['Age'].fillna(df_cleaned['Age'].median())

In [29]:

print(df_cleaned['Department'].value_counts())

Department
IT         3
Finance    3
HR         2
Name: count, dtype: int64

In [30]:
avg_salary_by_dept = df_cleaned.groupby('Department')['Salary'].mean()
print("Average Salary by Department:")
print(avg_salary_by_dept)

Average Salary by Department:
Department
Finance    83333.333333
HR         60000.000000
IT         53333.333333
Name: Salary, dtype: float64

In [31]:

print(df_cleaned[['Age', 'Salary']].corr())

             Age    Salary
Age     1.000000  0.993032
Salary  0.993032  1.000000